import 'dart:async';

import 'package:lean_builder/runner.dart' show BuilderEntry;
import 'package:lean_builder/src/asset/package_file_resolver.dart';
import 'package:lean_builder/src/graph/asset_scan_manager.dart';
import 'package:lean_builder/src/graph/assets_graph.dart';
import 'package:lean_builder/src/graph/scan_results.dart';
import 'package:lean_builder/src/logger.dart';
import 'package:lean_builder/src/resolvers/parsed_units_cache.dart';
import 'package:lean_builder/src/resolvers/resolver.dart';
import 'package:lean_builder/src/runner/build_phase.dart' show BuildPhase;
import 'package:lean_builder/src/runner/build_result.dart';
import 'package:lean_builder/src/runner/build_utils.dart';
import 'package:lean_builder/src/runner/command/base_command.dart';
import 'package:lean_builder/src/runner/command/utils.dart';

import 'lean_command_runner.dart';

class BuildCommand extends BaseCommand<int> {
  @override
  String get name => 'build';

  @override
  String get description => 'Executes a one time build.';

  @override
  String get invocation => 'lean_builder build [options]';

  LeanCommandRunner get buildRunner => runner as LeanCommandRunner;

  bool get isDevMode => argResults?['dev'] == true;

  @override
  Future<int>? run() async {
    prepare();

    final fileResolver = PackageFileResolver.forRoot();
    var assetsGraph = AssetsGraph.init(fileResolver.packagesHash);

    if (assetsGraph.shouldInvalidate) {
      Logger.info('Cache is invalidated, deleting old outputs...');
      _deleteExistingOutputs(assetsGraph, fileResolver);
      assetsGraph = AssetsGraph(assetsGraph.hash);
    }
    if (isDevMode) {
      assetsGraph.invalidateProcessedAssetsOf(fileResolver.rootPackage);
    }

    final sourceParser = SourceParser();
    final resolver = ResolverImpl(assetsGraph, fileResolver, sourceParser);
    final assets = assetsGraph.getProcessableAssets(fileResolver);
    return onRun(assets, resolver);
  }

  Future<int> onRun(Set<ProcessableAsset> assets, ResolverImpl resolver) async {
    return processAssets(assets, resolver);
  }

  Future<int> processAssets(Set<ProcessableAsset> assets, ResolverImpl resolver) async {
    final stopWatch = Stopwatch()..start();

    for (final entry in assets) {
      /// assume assets reaching this point are processed,
      /// if something goes wrong, we revert back to unprocessed
      if (entry.state != AssetState.deleted) {
        resolver.graph.updateAssetState(entry.asset.id, AssetState.processed);
      }
    }

    final rootAssets = List.of(
      assets.where((e) {
        final asset = e.asset;
        return asset.packageName == resolver.fileResolver.rootPackage;
      }),
    );

    if (rootAssets.isEmpty) {
      Logger.success('Build succeeded with no outputs ${stopWatch.elapsed.formattedMS}');
      return 0;
    }

    validateBuilderEntries(buildRunner.builderEntries);

    try {
      final outputCount = await build(assets: rootAssets, builders: buildRunner.builderEntries, resolver: resolver);
      await resolver.graph.save();
      Logger.success('Build succeeded in ${stopWatch.elapsed.formattedMS}, with ($outputCount) outputs');
      return 0;
    } catch (e, stk) {
      await resolver.graph.save();
      if (e is MultiFailedAssetsException) {
        for (final failure in e.assets) {
          Logger.error(failure.error.toString(), stackTrace: failure.stackTrace ?? stk);
        }
      } else {
        Logger.error(e.toString(), stackTrace: stk);
      }
      return 1;
    }
  }

  void _deleteExistingOutputs(AssetsGraph assetsGraph, PackageFileResolver fileResolver) {
    for (final entry in List.of(assetsGraph.outputs.entries)) {
      assetsGraph.updateAssetState(entry.key, AssetState.unProcessed);
      for (final output in entry.value) {
        final outputUri = assetsGraph.uriForAssetOrNull(output);
        if (outputUri == null) continue;
        assetsGraph.removeAsset(output);
        final outputAsset = fileResolver.assetForUri(outputUri);
        outputAsset.safeDelete();
      }
    }
  }

  Future<int> build({
    required List<ProcessableAsset> assets,
    required List<BuilderEntry> builders,
    required ResolverImpl resolver,
  }) async {
    assert(assets.isNotEmpty);

    final fileResolver = resolver.fileResolver;
    final graph = resolver.graph;

    final allOutputExtensions = builders.expand((e) => e.outputExtensions);

    for (final entry in List.of(assets)) {
      // handle deleted assets
      if (entry.state == AssetState.deleted) {
        graph.removeAsset(entry.asset.id);
        assets.remove(entry);
      }

      final outputs = graph.outputs[entry.asset.id];
      if (outputs != null) {
        for (final output in outputs) {
          final outputUri = graph.uriForAssetOrNull(output);
          if (outputUri == null) continue;
          if (!allOutputExtensions.any((e) => outputUri.path.endsWith(e))) {
            // this output is not generated by any builder, so we need to delete it now
            graph.removeAsset(output);
            assets.removeWhere((entry) => entry.asset.id == output);
            fileResolver.assetForUri(outputUri).safeDelete();
          }
        }
      }
    }

    if (assets.isEmpty) return 0;

    int outputCount = 0;
    final phases = calculateBuilderPhases(builders);
    final assetsToProcess = Set.of(assets);
    for (var i = 0; i < phases.length; i++) {
      final phase = phases[i];
      final buildPhase = BuildPhase(resolver, phase);
      buildPhase.beforeBuild(resolver, assets);
      final result = await buildPhase.build(assetsToProcess);
      if (result.hasErrors) {
        for (final entry in result.failedAssets) {
          graph.updateAssetState(entry.asset.id, AssetState.unProcessed);
        }
        // todo: decide if we should throw here, all or just first
        throw MultiFailedAssetsException(result.failedAssets.take(1).toList());
      }

      outputCount += result.outputs.length;
      if (result.containsAnyChanges) {
        final nextPhase = i + 1 < phases.length ? phases[i + 1] : null;
        if (nextPhase != null) {
          for (final builder in phase) {
            // skip if this builder did not do anything
            if (!result.containsChangesFromBuilder(builder)) continue;

            for (final nextBuilder in nextPhase) {
              if (builder.applies.contains(nextBuilder.key)) {
                final packageAssets = graph.getAssetsForPackage(fileResolver.rootPackage);
                for (final asset in packageAssets) {
                  if (nextBuilder.outputExtensions.any((e) => asset.uri.path.endsWith(e))) {
                    final srcGenerator = graph.getGeneratorOfOutput(asset.id);
                    if (srcGenerator != null) {
                      // mark the source as unprocessed to force the next phase to reprocess it
                      graph.updateAssetState(srcGenerator, AssetState.unProcessed);
                    }
                  }
                }
              }
            }
          }
        }
      }
      // add new outputs to the assets to be processed by the next phase
      final newAssets = graph.getProcessableAssets(fileResolver);
      assetsToProcess.addAll(newAssets);
      // we assume that the new assets will be processed in the next phase
      // if something goes wrong, we revert back to unprocessed
      for (final entry in newAssets) {
        if (entry.state != AssetState.deleted) {
          graph.updateAssetState(entry.asset.id, AssetState.processed);
        }
      }
    }
    return outputCount;
  }
}
